# Generated by Django 4.1.3 on 2023-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid_through',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_session_id',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Stripe session id'
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.IntegerField(
                choices=[(1, 'Success'), (2, 'Error'), (3, 'Process')],
                default=3,
                verbose_name='Paid status',
            ),
        ),
    ]
