# Generated by Django 4.1.3 on 2023-07-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0015_currency'),
        ('billing', '0003_invoice_date_completed_transaction_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transaction_currency',
                to='data.currency',
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.IntegerField(
                choices=[(1, 'Success'), (2, 'Error'), (3, 'Process'), (4, 'Canceled')],
                default=3,
                verbose_name='Paid status',
            ),
        ),
    ]
