# Generated by Django 4.1.3 on 2023-07-18 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0004_transaction_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
