# Generated by Django 4.1.3 on 2023-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0005_remove_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_notification_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Email notification date'
            ),
        ),
    ]
