# Generated by Django 4.1.3 on 2022-12-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'cost',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Cost'
                    ),
                ),
                ('describe', models.TextField(blank=True, verbose_name='Describe')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                (
                    'amount_days',
                    models.IntegerField(default=31, verbose_name='Amount days'),
                ),
            ],
        ),
    ]
