# Generated by Django 4.1.3 on 2022-12-28 18:08

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='describe',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Describe'),
        ),
    ]
