# Generated by Django 4.1.3 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(
                choices=[
                    ('success', 'success'),
                    ('info', 'info'),
                    ('warning', 'warning'),
                    ('error', 'error'),
                    ('paid', 'paid'),
                    ('unpaid', 'unpaid'),
                    ('canceled', 'canceled'),
                ],
                db_index=True,
                default='info',
                max_length=20,
                verbose_name='level',
            ),
        ),
    ]
