# Generated by Django 4.1.3 on 2022-12-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('describe', models.TextField(verbose_name='Describe')),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'rating',
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 'Like'), (2, 'Dislike')],
                        null=True,
                        verbose_name='Ticket rating',
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            (1, 'To Do'),
                            (2, 'In progress'),
                            (3, 'Done'),
                            (4, 'Close'),
                        ],
                        default=1,
                        verbose_name='Ticket status',
                    ),
                ),
                (
                    'assigned',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_assigned',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_author',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_department',
                        to='support.department',
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_service',
                        to='service.service',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TicketChat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                (
                    'rating',
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 'Like'), (2, 'Dislike')],
                        null=True,
                        verbose_name='Ticket chat message rating',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_chat_author',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ticket',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ticket_chat',
                        to='support.ticket',
                    ),
                ),
            ],
        ),
    ]
