# Generated by Django 4.1.3 on 2022-12-28 18:14

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0002_alter_ticket_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='describe',
            field=tinymce.models.HTMLField(verbose_name='Describe'),
        ),
    ]
