# Generated by Django 4.1.3 on 2022-12-28 18:38

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0003_alter_department_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchat',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Message'),
        ),
    ]
