# Generated by Django 4.1.3 on 2023-01-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0003_hearfromus'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alma_mater',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_alma_mater',
                to='data.almamater',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.ManyToManyField(
                related_name='profile_expertise', to='data.expertise'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hear_from_us',
            field=models.ManyToManyField(
                related_name='profile_hear_from_us', to='data.hearfromus'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Instagram'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(
                related_name='profile_interest', to='data.interest'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='First name'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Last name'
            ),
        ),
    ]
