# Generated by Django 4.1.3 on 2023-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_alter_account_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_subscription_payment_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Last subscription payment date'
            ),
        ),
    ]
