# Generated by Django 4.1.3 on 2023-04-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0005_adoptedactor_date_departments_documents_jurisdiction_and_more'),
        ('account', '0006_account_last_subscription_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adopted_actor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_adopted_actor',
                to='data.adoptedactor',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_date',
                to='data.date',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_departments',
                to='data.departments',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='documents',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_documents',
                to='data.documents',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='jurisdiction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_jurisdiction',
                to='data.jurisdiction',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='practice',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_practice',
                to='data.practice',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_sector',
                to='data.sector',
            ),
        ),
    ]
