# Generated by Django 4.1.3 on 2023-05-01 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0007_profile_adopted_actor_profile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adopted_actor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sector',
        ),
    ]
