# Generated by Django 4.1.3 on 2023-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_alter_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Real name'
            ),
        ),
    ]
