# Generated by Django 4.1.3 on 2023-05-25 06:03

from django.db import migrations, models

import apps.account.models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0011_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.account.models.user_upload_avatar_path,
                verbose_name='Avatar',
            ),
        ),
    ]
