# Generated by Django 4.1.3 on 2023-05-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0007_language'),
        ('account', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_language',
                to='data.language',
            ),
        ),
    ]
