# Generated by Django 4.1.3 on 2023-05-26 07:24

import django.db.models.deletion
from django.db import migrations, models

import apps.account.models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0008_lawyercasestatus'),
        ('account', '0013_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerCase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(blank=True, max_length=255, verbose_name='Title'),
                ),
                (
                    'client_name',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Client name'
                    ),
                ),
                (
                    'project_description',
                    models.TextField(blank=True, verbose_name='Project description'),
                ),
                (
                    'service_description',
                    models.TextField(blank=True, verbose_name='Service description'),
                ),
                ('impact', models.TextField(blank=True, verbose_name='Impact')),
                (
                    'decision_link',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Decision link'
                    ),
                ),
                (
                    'decision',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.account.models.user_upload_file_path,
                        verbose_name='Decision',
                    ),
                ),
                (
                    'jurisdiction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lawyer_case_jurisdiction',
                        to='data.jurisdiction',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lawyer_case_status',
                        to='data.lawyercasestatus',
                    ),
                ),
            ],
        ),
    ]
