# Generated by Django 4.1.3 on 2023-05-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0014_lawyercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyercase',
            name='account',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lawyer_case_account',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
