# Generated by Django 4.1.3 on 2023-05-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0015_lawyercase_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.CharField(blank=True, max_length=255)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specialization_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
