# Generated by Django 4.1.3 on 2023-05-26 12:25

import phonenumber_field.modelfields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0018_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'mobile_phone_number',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=100,
                        null=True,
                        region=None,
                        verbose_name='Mobile phone number',
                    ),
                ),
                (
                    'email',
                    models.EmailField(blank=True, max_length=255, verbose_name='Email'),
                ),
                (
                    'address',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Address'
                    ),
                ),
                (
                    'work_phone_number',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=100,
                        null=True,
                        region=None,
                        verbose_name='Work phone number',
                    ),
                ),
                (
                    'website',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Website'
                    ),
                ),
                (
                    'instagram',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Instagram'
                    ),
                ),
                (
                    'facebook',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Facebook'
                    ),
                ),
                (
                    'linkedin',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Linkedin'
                    ),
                ),
                (
                    'telegram',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Telegram'
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contact_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
