# Generated by Django 4.1.3 on 2023-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0019_remove_profile_facebook_remove_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Whatsapp'),
        ),
    ]
