# Generated by Django 4.1.3 on 2023-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0020_contact_twitter_contact_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
