# Generated by Django 4.1.3 on 2023-06-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.account.models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0010_degree_employmenttype_lawyerarea_lawyersource_and_more'),
        ('account', '0021_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_description',
            field=models.TextField(blank=True, verbose_name='Experience description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_visibility',
            field=models.BooleanField(default=True, verbose_name='Online visibility'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_display',
            field=models.BooleanField(default=True, verbose_name='Phone display'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_profession',
                to='data.profession',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Rate',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_visibility',
            field=models.BooleanField(default=True, verbose_name='Search visibility'),
        ),
        migrations.CreateModel(
            name='LawyerService',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(blank=True, max_length=255, verbose_name='Title'),
                ),
                (
                    'price',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='Price',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_service_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerRating',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'credential',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Credential'
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_rating_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'area',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_rating_area',
                        to='data.lawyerarea',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_rating_source',
                        to='data.lawyersource',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerPublication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'media',
                    models.CharField(blank=True, max_length=255, verbose_name='Media'),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateTimeField(verbose_name='Date')),
                (
                    'link',
                    models.CharField(blank=True, max_length=255, verbose_name='Link'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_publication_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerPublicActivity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'organisation',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Organisation'
                    ),
                ),
                (
                    'role',
                    models.CharField(blank=True, max_length=255, verbose_name='Role'),
                ),
                ('dates', models.CharField(max_length=255, verbose_name='Dates')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_public_activity_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lawyer_public_activity_country',
                        to='data.country',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerLicense',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(blank=True, max_length=255, verbose_name='Name'),
                ),
                (
                    'issuing_organisation',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Issuing organisation'
                    ),
                ),
                (
                    'credential',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Credential'
                    ),
                ),
                ('issue_date', models.DateTimeField(verbose_name='Issue date')),
                (
                    'expiration_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Expiration date'
                    ),
                ),
                (
                    'infinite',
                    models.BooleanField(default=False, verbose_name='Infinite'),
                ),
                (
                    'license_file',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.account.models.user_upload_license_path,
                        verbose_name='License file',
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_license_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lawyer_license_city',
                        to='data.city',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerExperience',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Position'
                    ),
                ),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='End date'
                    ),
                ),
                (
                    'still_here',
                    models.BooleanField(default=False, verbose_name='Still here'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_experience_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'employment_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employment_type_account',
                        to='data.employmenttype',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerEducation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'university_name',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='University name'
                    ),
                ),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='End date'
                    ),
                ),
                (
                    'still_here',
                    models.BooleanField(default=False, verbose_name='Still here'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'diploma_id',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Diploma id'
                    ),
                ),
                (
                    'diploma',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.account.models.user_upload_diploma_path,
                        verbose_name='Diploma',
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_education_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lawyer_education_city',
                        to='data.city',
                    ),
                ),
                (
                    'degree',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_education_degree',
                        to='data.degree',
                    ),
                ),
                (
                    'specialization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_education_specialization',
                        to='data.lawyerspecialization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LawyerAward',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'organisation',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Organisation'
                    ),
                ),
                ('issue_date', models.DateTimeField(verbose_name='Issue date')),
                (
                    'award',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.account.models.user_upload_award_path,
                        verbose_name='Award',
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_award_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalLanguages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.CharField(blank=True, max_length=255)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='additional_languages_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
