# Generated by Django 4.1.3 on 2023-06-04 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0022_profile_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hear_from_us',
        ),
    ]
