# Generated by Django 4.1.3 on 2023-06-08 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0010_degree_employmenttype_lawyerarea_lawyersource_and_more'),
        ('account', '0023_remove_profile_hear_from_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_languages',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='profile_additional_languages',
                to='data.language',
            ),
        ),
        migrations.AlterField(
            model_name='lawyercase',
            name='jurisdiction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_case_jurisdiction',
                to='data.country',
            ),
        ),
        migrations.CreateModel(
            name='LawyerJurisdictions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.CharField(blank=True, max_length=255)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lawyer_jurisdictions_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
