# Generated by Django 4.1.3 on 2023-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0024_profile_additional_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(default={}, verbose_name='Interests'),
        ),
    ]
