# Generated by Django 4.1.3 on 2023-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0025_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jurisdictions',
            field=models.JSONField(default={}, verbose_name='Jurisdictions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(default={}, verbose_name='Specializations'),
        ),
    ]
