# Generated by Django 4.1.3 on 2023-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0026_profile_jurisdictions_profile_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(default=dict, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jurisdictions',
            field=models.JSONField(default=dict, verbose_name='Jurisdictions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(default=dict, verbose_name='Specializations'),
        ),
    ]
