# Generated by Django 4.1.3 on 2023-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'account',
            '0027_alter_profile_interests_alter_profile_jurisdictions_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(default=list, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jurisdictions',
            field=models.JSONField(default=list, verbose_name='Jurisdictions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(default=list, verbose_name='Specializations'),
        ),
    ]
