# Generated by Django 4.1.3 on 2023-06-10 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'account',
            '0028_alter_profile_interests_alter_profile_jurisdictions_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additional_languages',
        ),
    ]
