# Generated by Django 4.1.3 on 2023-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0030_profile_additional_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_languages',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Additional languages'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Interests'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jurisdictions',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Jurisdictions'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Specializations'
            ),
        ),
    ]
