# Generated by Django 4.1.3 on 2023-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0031_alter_profile_additional_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Phone number'
            ),
        ),
    ]
