# Generated by Django 4.1.3 on 2023-06-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0010_degree_employmenttype_lawyerarea_lawyersource_and_more'),
        ('account', '0032_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alma_mater',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='lawyereducation',
            name='country',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_education_country',
                to='data.country',
            ),
        ),
    ]
