# Generated by Django 4.1.3 on 2023-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0033_remove_profile_alma_mater_remove_profile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additional_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Languages'
            ),
        ),
    ]
