# Generated by Django 4.1.3 on 2023-06-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0010_degree_employmenttype_lawyerarea_lawyersource_and_more'),
        ('account', '0034_remove_profile_additional_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='practice',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_practice',
                to='data.practice',
            ),
        ),
    ]
