# Generated by Django 4.1.3 on 2023-06-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0011_fileupload'),
        ('account', '0035_profile_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profile_avatar',
                to='data.fileupload',
            ),
        ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='avatar',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatar', to='data.fileupload'),
        # ),
    ]
