# Generated by Django 4.1.3 on 2023-06-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0011_fileupload'),
        ('account', '0036_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyereducation',
            old_name='diploma_id',
            new_name='id_diploma',
        ),
        migrations.AlterField(
            model_name='lawyeraward',
            name='award',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_award_award',
                to='data.fileupload',
            ),
        ),
        migrations.AlterField(
            model_name='lawyercase',
            name='decision',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_case_decision',
                to='data.fileupload',
            ),
        ),
        migrations.AlterField(
            model_name='lawyereducation',
            name='diploma',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_education_diploma',
                to='data.fileupload',
            ),
        ),
        migrations.AlterField(
            model_name='lawyerlicense',
            name='license_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_license_license_file',
                to='data.fileupload',
            ),
        ),
    ]
