# Generated by Django 4.1.3 on 2023-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0037_rename_diploma_id_lawyereducation_id_diploma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyereducation',
            name='specialization',
        ),
        migrations.AddField(
            model_name='lawyereducation',
            name='specializations',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Specializations'
            ),
        ),
    ]
