# Generated by Django 4.1.3 on 2023-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0038_remove_lawyereducation_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyereducation',
            name='specializations',
        ),
        migrations.AddField(
            model_name='lawyereducation',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
