# Generated by Django 4.1.3 on 2023-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0039_remove_lawyereducation_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone_number',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Mobile phone number',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone_number',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Work phone number'
            ),
        ),
    ]
