# Generated by Django 4.1.3 on 2023-06-15 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0040_alter_contact_mobile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
