# Generated by Django 4.1.3 on 2023-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0042_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Instagram'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_phone_number',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Mobile phone number',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_phone_number',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Work phone number'
            ),
        ),
    ]
