# Generated by Django 4.1.3 on 2023-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0043_profile_address_profile_email_profile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_phone_number',
        ),
    ]
