# Generated by Django 4.1.3 on 2023-06-17 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0045_profile_mobile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile_phone_number',
        ),
    ]
