# Generated by Django 4.1.3 on 2023-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0046_remove_contact_mobile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_number',
            field=models.CharField(
                blank=True, max_length=100, verbose_name='Mobile phone number'
            ),
        ),
    ]
