# Generated by Django 4.1.3 on 2023-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0047_contact_mobile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_phone_number',
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone_number',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Mobile phone number',
            ),
        ),
    ]
