# Generated by Django 4.1.3 on 2023-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0048_remove_profile_mobile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_phone_number',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Mobile phone number'
            ),
        ),
    ]
