# Generated by Django 4.1.3 on 2023-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0049_profile_mobile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyereducation',
            name='license_id',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='License id'
            ),
        ),
    ]
