# Generated by Django 4.1.3 on 2023-06-30 19:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

from apps.account.models import Profile


def compute_search_vector(apps, schema_editor):
    Profile.objects.update(
        search_vector=django.contrib.postgres.search.SearchVector(
            'real_name',
            'description',
            'experience_description',
            # 'profession__value',
            # 'practice__value',
            # 'country__name',
            # 'city__name',
            # 'expertise__value',
            'rate',
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0051_alter_profile_birthday_alter_profile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'], name='account_pro_search__0990c0_gin'
            ),
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
