# Generated by Django 4.1.3 on 2023-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0052_profile_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jurisdictions_text',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Jurisdictions text'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_text',
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name='Languages text'
            ),
        ),
    ]
