# Generated by Django 4.1.3 on 2023-07-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0014_alter_gender_options_gender_my_order'),
        ('account', '0053_profile_jurisdictions_text_profile_languages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerexperience',
            name='city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_experience_city',
                to='data.city',
            ),
        ),
        migrations.AddField(
            model_name='lawyerexperience',
            name='country',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_experience_country',
                to='data.country',
            ),
        ),
    ]
