# Generated by Django 4.1.3 on 2023-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0055_lawyerexperience_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyeraward',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
