# Generated by Django 4.1.3 on 2023-07-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0014_alter_gender_options_gender_my_order'),
        ('account', '0056_lawyeraward_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyerlicense',
            old_name='credential',
            new_name='credential_id',
        ),
        migrations.RemoveField(
            model_name='lawyerlicense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lawyerpublicactivity',
            name='dates',
        ),
        migrations.AddField(
            model_name='lawyerlicense',
            name='country',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_license_country',
                to='data.country',
            ),
        ),
        migrations.AddField(
            model_name='lawyerlicense',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='lawyerpublicactivity',
            name='city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lawyer_public_activity_city',
                to='data.city',
            ),
        ),
        migrations.AddField(
            model_name='lawyerpublicactivity',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='lawyerpublicactivity',
            name='start_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Start date'
            ),
        ),
        migrations.AddField(
            model_name='lawyerpublicactivity',
            name='still_here',
            field=models.BooleanField(default=False, verbose_name='Still here'),
        ),
    ]
