# Generated by Django 4.1.3 on 2023-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0057_rename_credential_lawyerlicense_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_access',
            field=models.BooleanField(default=False, verbose_name='Has access'),
        ),
    ]
