# Generated by Django 4.1.3 on 2023-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0058_account_has_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='has_access',
            field=models.BooleanField(default=True, verbose_name='Has access'),
        ),
    ]
