# Generated by Django 4.1.3 on 2023-07-19 12:45

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0059_alter_account_has_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
