# Generated by Django 4.1.3 on 2023-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0060_alter_profile_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_display',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_visibility',
            field=models.BooleanField(default=True, verbose_name='Phone visibility'),
        ),
    ]
