# Generated by Django 4.1.3 on 2023-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0061_remove_profile_phone_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sending_notifications',
            field=models.BooleanField(
                default=False, verbose_name='Sending notifications'
            ),
        ),
    ]
