# Generated by Django 4.1.3 on 2023-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0062_profile_sending_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sending_browser_notifications',
            field=models.BooleanField(
                default=False, verbose_name='Sending browser notifications'
            ),
        ),
    ]
