# Generated by Django 4.1.3 on 2023-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0002_country_region_subregion_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearFromUs',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
