# Generated by Django 4.1.3 on 2023-01-30 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0003_hearfromus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hearfromus',
            options={'verbose_name': 'HearFromUs', 'verbose_name_plural': 'HearFromUs'},
        ),
    ]
