# Generated by Django 4.1.3 on 2023-06-12 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.data.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0010_degree_employmenttype_lawyerarea_lawyersource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=apps.data.models.file_upload_path, verbose_name='File'
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='file_upload_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
