# Generated by Django 4.1.3 on 2023-06-18 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0012_alter_gender_options_gender_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='gender',
            name='my_order',
        ),
    ]
