# Generated by Django 4.1.3 on 2023-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0013_alter_gender_options_remove_gender_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('my_order',)},
        ),
        migrations.AddField(
            model_name='gender',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
